import './style.css';
import {chapters,useCases,assetInfo,stateAt,chapterProgress,useProgress,totalLength} from './content.js';
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
const arrow='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>';
const mark='<svg viewBox="0 0 38 38" fill="none" aria-hidden="true"><path d="m19 3 15 8v16l-15 8L4 27V11Z" stroke="currentColor" stroke-width="1.5"/><path d="m4 11 15 8 15-8M19 19v16" stroke="currentColor" stroke-width="1.5"/><path d="m19 9 9 5-9 5-9-5Z" fill="#c7ff3d"/></svg>';
document.querySelector('#app').innerHTML=`
<a class="skip" href="#story-title">Skip to story</a>
<header><a class="identity" href="#chapter-1" aria-label="City Intelligence, restart">${mark}<span>City<span class="identity-light">Intelligence</span></span></a><div class="header-center">From data to intelligent city operations</div><div class="header-actions"><button id="motion" aria-pressed="false">Reduced motion</button><button id="fullscreen" aria-label="Enter fullscreen">⛶</button></div></header>
<div class="progress-track"><div id="total-progress"></div></div>
<main id="experience"><div class="scene-shell"><div class="scene-ground"></div><div id="city-scene"></div><div class="scene-caption"><span class="status-dot"></span><span id="scene-state">A connected view of city life</span><span id="render-state">Preparing city</span></div><div class="scene-controls"><button id="return" hidden>Return to story</button><span>Drag gently to look around</span></div><div id="loader" role="status"><span>Building a shared perspective</span><progress max="100" value="15" aria-label="City loading progress"></progress></div></div>
<section class="story-copy" aria-labelledby="story-title"><div class="chapter-kicker"><span id="chapter-number">01 / 08</span><span id="chapter-name"></span></div><h1 id="story-title" tabindex="-1"></h1><p id="story-copy"></p><div id="chapter-extra"></div><p class="story-note" id="story-note"></p><button class="start-button" id="start">Explore the story ${arrow}</button></section>
<aside id="context" aria-label="Operational context"></aside>
<nav id="usecases" aria-label="Use case navigation" hidden>${useCases.map((u,i)=>`<button data-use="${i}"><span>0${i+1}</span>${u.name}</button>`).join('')}</nav>
<div class="locations"><span>Inspect a solution</span>${[['water','Water'],['traffic','Mobility'],['park','Environment'],['office','Buildings'],['hub','Operations']].map(([id,n])=>`<button data-asset="${id}">${n}<span>＋</span></button>`).join('')}</div>
<dialog id="details" aria-labelledby="detail-title"><button id="close-detail" aria-label="Close solution details">×</button><div id="detail-content"></div><p class="detail-disclosure">Illustrative workflow. No live systems or device control.</p></dialog>
<nav class="chapter-nav" aria-label="Chapter navigation">${chapters.map((c,i)=>`<button data-chapter="${i}" aria-label="Chapter ${i+1}: ${c.name}"><span>0${i+1}</span><i></i><b>${c.name}</b></button>`).join('')}</nav>
<footer><div class="footer-left"><span class="scroll-icon">↓</span><span id="scroll-label">Scroll to discover</span></div><div class="legend"><span><i class="lime"></i>Connected</span><span><i class="orchid"></i>Intelligence</span><span><i class="warn"></i>Warning</span><span><i class="critical"></i>Critical</span></div><div class="footer-controls"><button id="restart" aria-label="Restart presentation">↺</button><button id="previous" aria-label="Previous chapter">←</button><span id="footer-count">01 / 08</span><button id="next" aria-label="Next chapter">→</button></div></footer>
<p class="disclosure">Illustrative experience using mock data. Not connected to live systems.</p></main><div id="scroll-space" aria-hidden="true"></div><div id="announce" class="sr" aria-live="polite"></div>
<section class="mobile-summary"><img class="city-poster" src="/city-intelligence-poster.webp" alt="Isometric city with workplace towers, residences, an operations pavilion, a riverside park and bridges" loading="lazy" width="1600" height="1100"><h2>A city in perspective.</h2><p>Explore the complete 3D story on a desktop. This lightweight summary follows the same roadmap.</p>${chapters.map((c,i)=>`<article><span>0${i+1} / ${c.name}</span><h3>${c.title.replaceAll('\n',' ')}</h3><p>${c.copy}</p></article>`).join('')}</section>`;
$('#scroll-space').style.height=`${totalLength*100+100}vh`;
let scene=null,current=stateAt(0),lastKey='',reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,lastOpener=null;
$('#motion').setAttribute('aria-pressed',String(reduced));document.body.classList.toggle('reduced',reduced);
const miniChart=(v=0,color='orchid')=>`<svg class="spark ${color}" viewBox="0 0 240 52" aria-label="Illustrative trend"><path d="M0 42H240" class="baseline"/><path d="M0 38 24 36 48 39 72 32 96 34 120 27 144 28 168 ${28-v*10} 192 ${22-v*12} 216 ${20-v*14} 240 ${18-v*15}"/></svg>`;
function context(s){
 if(s.index===0)return `<div class="quiet-context"><span class="live-pill"><i></i>A living network</span><div class="signal-row"><span>Traffic</span><b>Moving</b></div><div class="signal-row"><span>Environment</span><b>Observed</b></div><div class="signal-row"><span>Infrastructure</span><b>Connected by place</b></div></div>`;
 if(s.index===1){const names=['GIS','CCTV & video','Traffic management','Building & energy','Incident & service','Environment & weather','Reports & spreadsheets'];return `<div class="system-silos"><p>Different systems. Different moments.</p>${names.map((n,i)=>`<div><i></i><span>${n}</span><small>${[2,12,4,18,7,3,60][i]} min ago</small></div>`).join('')}<p class="warning-text">Waterway event · awareness delayed</p></div>`;}
 if(s.index===2)return `<div class="platform-card"><span class="live-pill"><i></i>Shared operational context</span><h2>Many sources.<br>One perspective.</h2><ol>${['Data sources','Integration & APIs','Governed data platform','Analytics & Operational Twin','Operational applications'].map((x,i)=>`<li class="${s.local>i*.12?'on':''}"><span>0${i+1}</span>${x}</li>`).join('')}</ol><p class="governance">Security & governance across every layer</p></div>`;
 if(s.index===3)return `<div class="operation-card"><span class="card-label">Operational Digital Twin</span><h2>${s.local>.6?'Revisit the sequence.':'Give data a place.'}</h2><div class="layer-row"><b>Asset registry</b><span>Locations & relationships</span></div><div class="layer-row"><b>Event layer</b><span>Alerts in their physical context</span></div><div class="layer-row"><b>Historical playback</b><span>${s.local>.6?'Earlier observations selected':'Current observations selected'}</span></div><div class="timeline"><i style="left:${Math.round(s.local*90)}%"></i></div><p>Current state and history stay distinct. Predictive overlays arrive in Phase 3.</p></div>`;
 if(s.index===4)return `<div class="operation-card"><span class="card-label">Device health & freshness</span><h2>Signals with context.</h2>${[['Water level','0.82 m'],['Air quality','18 µg/m³'],['Traffic camera','Low density'],['Energy meter','420 kW'],['Weather station','0 mm/h']].map(([n,v],i)=>`<div class="sensor-row ${s.local>i*.13?'on':''}"><i></i><span>${n}<small>${s.local>i*.13?'Healthy · updated 12 sec ago':'Information gap identified'}</small></span><b>${s.local>i*.13?v:'—'}</b></div>`).join('')}<p>Illustrative near real-time observations.</p></div>`;
 if(s.index===5){const u=useCases[s.useIndex],value=[s.water.toFixed(2),s.traffic,s.air,s.energy,s.incident][s.useIndex];return `<div class="operation-card usecase-card"><span class="card-label">${String(s.useIndex+1).padStart(2,'0')} / 05 · ${u.name}</span><div class="metric"><span>${u.metric}</span><strong>${value}<small>${u.unit}</small></strong><p>${u.baseline}</p></div>${miniChart(s.u)}<div class="flow-copy"><span>Connect</span><p>${u.source}</p><span>Understand</span><p>${u.process}</p><span>Act</span><p>${u.action}</p></div><button class="detail-link" data-asset="${u.focus}">Inspect this solution ${arrow}</button></div>`;}
 if(s.index===6)return `<div class="operation-card prediction-card"><span class="card-label">Illustrative forecast</span><h2>30 minutes ahead.</h2><div class="comparison"><div><span>Observed now</span><strong>1.26<small>m</small></strong></div><div><span>Predicted +30 min</span><strong>${(1.26+s.forecast*.72).toFixed(2)}<small>m</small></strong></div></div>${miniChart(s.forecast)}<p class="warning-text">Rising faster than the historical pattern</p><ol class="recommendations"><li>Review exposed access roads</li><li>Verify field conditions with the team</li><li>Prepare response resources</li></ol><div class="demo-actions"><button disabled>Review</button><button disabled>Approve</button></div><p>Visual demonstration only. People remain responsible for every decision.</p>${s.local>.8?'<p class="energy-note">Energy anomaly · 548 kW vs 420 kW baseline. Inspection recommended; cause unconfirmed.</p>':''}</div>`;
 return `<div class="roadmap-card"><span class="card-label">Build on each phase</span><h2>Start focused.<br>Scale with purpose.</h2><ol>${['Connect existing data','Create operational visibility','Expand with IoT','Advance with AI','Measure and scale'].map((x,i)=>`<li><span>0${i+1}</span>${x}</li>`).join('')}</ol><p>Shared visibility. Earlier awareness.<br>More coordinated operations.</p></div>`;
}
function update(p){current=stateAt(p);const s=current,c=chapters[s.index];const key=`${s.index}-${s.useIndex}`;
 if(key!==lastKey){lastKey=key;$('#chapter-number').textContent=`${String(s.index+1).padStart(2,'0')} / 08`;$('#chapter-name').textContent=c.name;$('#story-title').textContent=s.index===5?useCases[s.useIndex].title:c.title;$('#story-copy').textContent=s.index===5?useCases[s.useIndex].copy:c.copy;$('#story-note').textContent=c.note;$('#start').hidden=s.index!==0;$('#usecases').hidden=s.index!==5;$('#footer-count').textContent=`${String(s.index+1).padStart(2,'0')} / 08`;$('#previous').disabled=s.index===0;$('#next').disabled=s.index===7;$('#scroll-label').textContent=s.index===7?'Restart to explore again':'Scroll to discover';$('#announce').textContent=`Chapter ${s.index+1}: ${c.name}`;$$('[data-chapter]').forEach((b,i)=>b.setAttribute('aria-current',i===s.index?'step':'false'));$$('[data-use]').forEach((b,i)=>b.setAttribute('aria-current',i===s.useIndex?'step':'false'));document.body.dataset.chapter=s.index;}
 $('#total-progress').style.width=`${s.p*100}%`;$('#context').innerHTML=context(s);$('#scene-state').textContent=s.index===6?'Current observations + predicted impact':s.index===1?'Disconnected systems':s.index>=2?'One shared operational view':'A connected view of city life';
 $('#return').hidden=true;scene?.update(s,reduced);
}
function scrollP(){return window.scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight);}
let pending=false;addEventListener('scroll',()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;update(scrollP());});},{passive:true});
function jump(p){window.scrollTo({top:p*(document.documentElement.scrollHeight-innerHeight),behavior:'instant'});update(p);}
function chapter(i){const n=Math.max(0,Math.min(7,i));jump(chapterProgress(n)+.0001);history.replaceState(null,'',`#chapter-${n+1}`);}
$('#start').onclick=()=>chapter(1);$('#next').onclick=()=>chapter(current.index+1);$('#previous').onclick=()=>chapter(current.index-1);$('#restart').onclick=()=>chapter(0);$('.identity').onclick=e=>{e.preventDefault();chapter(0);};
$('#motion').onclick=()=>{reduced=!reduced;$('#motion').setAttribute('aria-pressed',String(reduced));document.body.classList.toggle('reduced',reduced);scene?.update(current,reduced);};
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{$('#announce').textContent='Fullscreen is unavailable in this browser.';}};
addEventListener('fullscreenchange',()=>{$('#fullscreen').setAttribute('aria-label',document.fullscreenElement?'Exit fullscreen':'Enter fullscreen');scene?.resize();});
$('#return').onclick=()=>{scene?.restore();$('#return').hidden=true;};
function closeDetail(){$('#details').close();scene?.restore();lastOpener?.focus();}
$('#close-detail').onclick=closeDetail;$('#details').addEventListener('cancel',()=>{scene?.restore();lastOpener?.focus();});
function inspect(id,opener){const a=assetInfo[id];if(!a)return;lastOpener=opener||document.activeElement;$('#detail-content').innerHTML=`<span class="card-label">${a.type}</span><h2 id="detail-title">${a.name}</h2><div class="detail-model-icon">${mark}</div><ol class="detail-steps"><li><span>01 / Data source</span><p>${a.source}</p></li><li><span>02 / Platform context</span><p>${a.process}</p></li><li><span>03 / Operational decision</span><p>${a.action}</p></li></ol>`;scene?.focus(a.focus);$('#details').showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.chapter!==undefined)chapter(+b.dataset.chapter);if(b.dataset.use!==undefined)jump(useProgress(+b.dataset.use));if(b.dataset.asset)inspect(b.dataset.asset,b);});
addEventListener('keydown',e=>{if($('#details').open||['BUTTON','INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='ArrowRight'){e.preventDefault();chapter(current.index+1);}if(e.key==='ArrowLeft'){e.preventDefault();chapter(current.index-1);}});
update(0);
async function init(){
 if(matchMedia('(max-width: 700px)').matches){$('#loader').hidden=true;$('#render-state').textContent='Lightweight story';return;}
 try{$('#loader progress').value=35;const {mountScene}=await import('./scene.js');$('#loader progress').value=65;scene=await mountScene($('#city-scene'),{select:id=>inspect(id),manual:()=>$('#return').hidden=false,ready:label=>{$('#render-state').textContent=label;$('#loader progress').value=100;$('#loader').hidden=true;}});scene.update(current,reduced);}
 catch(error){console.error('City scene could not start',error);$('#loader').innerHTML='<span>The 3D view is unavailable. The complete story remains below.</span>';document.body.classList.add('fallback');}
 const hash=location.hash.match(/^#chapter-([1-8])$/);if(hash)chapter(+hash[1]-1);else update(scrollP());
}
init();
