export const sections=[
 {id:'overview',phase:'The city today',title:'Different places.\nOne connected city.',intro:'A hospital, a school, a waterway and a transport team all serve the same community. Their information should work together, too.',points:[['Places','See the real-world locations behind the data.'],['Teams','Understand who needs the information.'],['Decisions','Follow how a shared picture helps the next action.']],takeaway:'This is a 3D model of an illustrative city. Every value in this presentation is mock data.'},
 {id:'fragmented',phase:'The problem',title:'The water team sees a warning.\nThe road team does not.',intro:'Heavy rain is approaching. Water readings, camera events and road information sit in separate systems. Teams have to piece the situation together.',points:[['Water system','The level is rising near the flood gate.'],['Camera system','A nearby access road is still in use.'],['Separate reports','The operations team has no shared incident record.']],takeaway:'The problem is disconnected information, not a lack of data.'},
 {id:'foundation',phase:'Phase 1 / Data Consolidation',title:'Start with the systems\nyou already have.',intro:'Connect existing maps, asset records, camera events and operational reports. Show the same place and the same incident to every responsible team.',points:[['Bring sources together','GIS, CCTV, building systems, service records and reports.'],['Check and organize','Confirm locations, ownership, data quality and access rights.'],['Create a shared view','Show assets, events and earlier observations in an Operational Digital Twin.']],takeaway:'Result: one location-aware view. Existing systems remain in place.'},
 {id:'iot',phase:'Phase 2 / IoT Data Integration',title:'Add sensors where\ninformation is missing.',intro:'Fill specific gaps with water, air-quality, weather and energy sensors. Show when each reading arrived and whether the device is healthy.',points:[['Water level','1.20 m · updated 12 seconds ago'],['Air quality','PM2.5 18 µg/m³ · updated 30 seconds ago'],['Energy','420 kW · updated 20 seconds ago']],takeaway:'Result: fresher field observations, with clear timestamps and device health.'},
 {id:'flood',phase:'A practical example / Flood response',title:'One warning.\nA clear next step.',intro:'The city now connects the water reading to nearby roads and the team responsible. The same incident appears in the command center.',points:[['1. Detect','A 1.60 m reading exceeds the illustrative 1.40 m warning threshold.'],['2. Understand','Locate the affected waterway and the access road beside it.'],['3. Coordinate','Ask the response team to verify conditions and review a safer route.']],takeaway:'Result: teams work from the same event and location. No real device is controlled.'},
 {id:'priorities',phase:'One platform / Multiple priorities',title:'Use the same foundation\nacross the city.',intro:'The connected view also supports transport, environment, energy and public services. Select a district below to see its role.',points:[['Transport','Connect congestion, camera event metadata and road context.'],['Environment and energy','Compare air-quality trends and unusual consumption.'],['Public services','Link the incident, its location and the assigned team.']],takeaway:'Each use case adds context to the same city and data foundation.'},
 {id:'ai',phase:'Phase 3 / AI-Powered Intelligence',title:'What could happen next?\nHelp people prepare.',intro:'With reliable data and enough history, show an illustrative forecast beside current conditions. A person reviews the recommendation before taking action.',points:[['Observe now','Water level: 1.60 m.'],['Look ahead','Illustrative forecast in 30 minutes: 1.90 m.'],['Recommend','Review the exposed road, verify field conditions and prepare response resources.']],takeaway:'Result: earlier awareness. AI recommends; people remain responsible for decisions.'},
 {id:'roadmap',phase:'The roadmap',title:'Connect first.\nExpand with purpose.',intro:'Begin with one priority and a small set of existing systems. Add sensors where they help. Introduce measurable AI use cases when the information is ready.',points:[['Phase 1','Data Consolidation → a shared operational view.'],['Phase 2','IoT Data Integration → fresher field visibility.'],['Phase 3','AI-Powered Intelligence → forecasts and recommendations.']],takeaway:'Connect existing data. See every situation. Scale from IoT to AI.'},
];
export const places={
 civic:{name:'Civic administration',source:'Maps, service requests and asset records.',work:'Link each request to a place and the responsible department.',outcome:'Give the operations team a shared record of ownership and progress.'},
 hospital:{name:'Hospital',source:'Facility status, energy readings and service events.',work:'Put building conditions beside access roads and local incidents.',outcome:'Help facility and response teams coordinate using the same situation.'},
 school:{name:'Education',source:'Campus asset records and incident reports.',work:'Link a reported issue to the campus and assigned service team.',outcome:'Track who is responsible and what has been resolved.'},
 tourism:{name:'Park and tourism',source:'Environmental readings, weather and public-service reports.',work:'Show observations beside the park and water features.',outcome:'Help the environmental team locate and investigate changes.'},
 industry:{name:'Industry',source:'Facility events, meters and environmental observations.',work:'Compare field conditions and reported exceptions by location.',outcome:'Coordinate review with the responsible facility team.'},
 energy:{name:'Clean energy',source:'Power readings and renewable asset status.',work:'Compare production, demand and the historical operating pattern.',outcome:'Focus an inspection on a meaningful exception.'},
 transit:{name:'Transport',source:'Traffic observations, camera event metadata and road maps.',work:'Connect a congestion report to its corridor and nearby incident.',outcome:'Review route options with the traffic team.'},
 water:{name:'Water and flood prevention',source:'Water level, rainfall and flood-gate asset records.',work:'Compare the reading with a threshold and locate nearby exposed roads.',outcome:'Ask the response team to verify conditions and review access.'},
 housing:{name:'Neighbourhood',source:'Building locations and service reports.',work:'Place requests into geographic and asset context.',outcome:'Give residents’ service teams a consistent incident history.'},
 command:{name:'CDP Command Center',source:'Existing systems, IoT observations and operational records.',work:'Check, organize and link information to common locations and events.',outcome:'Create a shared operational picture for people to review and act on.'},
};
