const canvas=document.querySelector('#scene');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x09111f);scene.fog=new THREE.FogExp2(0x09111f,.015);
const camera=new THREE.PerspectiveCamera(34,innerWidth/innerHeight,.1,240);camera.position.set(33,23,39);
const controls={target:new THREE.Vector3(3,11,0),autoRotate:false,autoRotateSpeed:.45,enabled:true,theta:Math.atan2(33,39),phi:Math.acos((23-11)/Math.hypot(33,12,39)),radius:Math.hypot(33,12,39),update(){if(!this.enabled)return;if(this.autoRotate)this.theta+=.0018*this.autoRotateSpeed;const s=Math.sin(this.phi);camera.position.set(this.target.x+this.radius*s*Math.sin(this.theta),this.target.y+this.radius*Math.cos(this.phi),this.target.z+this.radius*s*Math.cos(this.theta));camera.lookAt(this.target)}};
let drag=false,px=0,py=0;canvas.addEventListener('pointerdown',e=>{drag=true;px=e.clientX;py=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;controls.theta-=(e.clientX-px)*.006;controls.phi=Math.max(.35,Math.min(1.7,controls.phi+(e.clientY-py)*.005));px=e.clientX;py=e.clientY});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('wheel',e=>{controls.radius=Math.max(22,Math.min(72,controls.radius+e.deltaY*.025))},{passive:true});
const root=new THREE.Group();root.position.set(5,-8,0);scene.add(root);

const M={concrete:new THREE.MeshStandardMaterial({color:0xd9e0e5,roughness:.72,metalness:.02}),dark:new THREE.MeshStandardMaterial({color:0x23313e,roughness:.34,metalness:.72}),glass:new THREE.MeshPhysicalMaterial({color:0x7bb3cf,roughness:.12,metalness:.05,transmission:.35,transparent:true,opacity:.43,depthWrite:false,thickness:.35}),warm:new THREE.MeshStandardMaterial({color:0xffb96e,emissive:0xff8a35,emissiveIntensity:1.15,roughness:.65}),cyan:new THREE.MeshStandardMaterial({color:0x38d9f5,emissive:0x0bb5d6,emissiveIntensity:2.2,roughness:.28}),green:new THREE.MeshStandardMaterial({color:0x4e735e,roughness:.9}),wood:new THREE.MeshStandardMaterial({color:0x8d6a4e,roughness:.7}),road:new THREE.MeshStandardMaterial({color:0x111c27,roughness:.92}),red:new THREE.MeshStandardMaterial({color:0xff5d62,emissive:0xdd2028,emissiveIntensity:2})};
function box(name,size,pos,mat,parent=root,bevel=false){const g=new THREE.BoxGeometry(...size);const m=new THREE.Mesh(g,mat);m.name=name;m.position.set(...pos);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function cyl(name,r,d,pos,mat,parent=root){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,d,20),mat);m.name=name;m.position.set(...pos);m.castShadow=true;parent.add(m);return m}
function windowRow(parent,y,z,front=true){for(let x=-7.1;x<=7.1;x+=2.05){box('warm-office-light',[1.58,.11,.04],[x,y,z],M.warm,parent)}}
const building=new THREE.Group();building.name='ConfigurableOfficeTower';root.add(building);
// site and podium
box('site',[66,.35,52],[0,-.25,0],M.road);box('podium',[21,.55,15],[0,.15,0],M.concrete,building);
for(const [x,z,s] of [[-14,7,1.2],[-11,-7,.9],[13,-8,1.1],[16,5,.8],[-17,-3,.7]]){cyl('tree-trunk',.12,1.5,[x,.7,z],M.wood);const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(s,1),M.green);crown.position.set(x,2,z);crown.castShadow=true;root.add(crown)}
const floors=[];const FH=2.45,COUNT=9;
for(let i=0;i<COUNT;i++){const y=.65+i*FH;const floor=new THREE.Group();floor.name=i===0?'Lobby':i===8?'MeetingFloor':`OfficeFloor_${i}`;floor.position.y=y;building.add(floor);floors.push(floor);box('slab',[17.4,.25,11.8],[0,0,0],M.concrete,floor);box('core',[3.1,FH-0.15,3.4],[1,FH/2,-1.2],M.concrete,floor);box('glass-shell',[17,FH-0.35,11.35],[0,FH/2,0],M.glass,floor);for(let x=-7.8;x<=7.8;x+=2){box('facade-fin',[.10,FH,.36],[x,FH/2,5.85],M.dark,floor);box('facade-fin',[.10,FH,.36],[x,FH/2,-5.85],M.dark,floor)}for(let z=-4.8;z<=4.8;z+=2){box('side-fin',[.34,FH,.10],[-8.65,FH/2,z],M.dark,floor);box('side-fin',[.34,FH,.10],[8.65,FH/2,z],M.dark,floor)}windowRow(floor,FH*.66,5.68);if(i>0){for(let x=-6;x<=6;x+=3){box('desk',[1.5,.08,.7],[x,.55,1.2],M.wood,floor);box('task-light',[.55,.04,.12],[x,.9,1.2],M.warm,floor)}}}
// lobby canopy and sculptural columns
box('entrance-canopy',[11,.24,4],[0,3.0,7.25],M.concrete,building);for(const x of [-4.7,4.7])cyl('canopy-column',.13,2.8,[x,1.55,8.55],M.dark,building);
// sky gardens break the tower silhouette
for(const level of [3,6]){const y=.65+level*FH+.2;box('sky-terrace',[19,.3,13],[0,y,0],M.concrete,building);for(const x of [-6,-2,3,6]){box('planter',[1.6,.5,.8],[x,y+.35,5.8],M.dark,building);const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(.52,1),M.green);crown.position.set(x,y+1,5.8);building.add(crown)}}
// crown, solar panels, rooftop plant
const roofY=.65+COUNT*FH;box('roof',[18,.4,12.4],[0,roofY,0],M.concrete,building);for(let x=-6;x<=6;x+=3)for(let z=-3;z<=3;z+=2){const p=box('solar-panel',[2.3,.10,1.35],[x,roofY+.55,z],M.dark,building);p.rotation.x=-.18}box('crown-frame',[8,2.4,.28],[0,roofY+1.4,-5.7],M.dark,building);
// basements / plant room below podium
const plant=new THREE.Group();plant.name='PlantRoom_B2';plant.position.y=-4.9;building.add(plant);box('plant-room',[17,4.2,11],[0,0,0],new THREE.MeshStandardMaterial({color:0x152536,roughness:.72,side:THREE.BackSide}),plant);
for(let x=-5.3;x<=4.8;x+=5.1){cyl('chiller',1.05,3.4,[x,0,0],M.dark,plant).rotation.z=Math.PI/2;for(const z of [-1.1,1.1])cyl('pipe',.18,9,[x,1.55,z],M.cyan,plant).rotation.z=Math.PI/2}box('plant-floor',[17,.3,11],[0,-2.05,0],M.concrete,plant);const alert=box('chiller-alert',[.4,.4,.4],[5,1.2,1.4],M.red,plant);alert.visible=false;
// cyan systems / vertical nervous system
const signalGroup=new THREE.Group();signalGroup.name='DigitalTwinOverlay';building.add(signalGroup);for(let i=1;i<COUNT;i++){const y=.65+i*FH+1.25;for(const x of [-6,6]){const s=new THREE.Mesh(new THREE.SphereGeometry(.12,16,10),M.cyan);s.position.set(x,y,5.9);signalGroup.add(s)}}const spine=cyl('data-spine',.035,roofY+4,[8.9,roofY/2-1,0],M.cyan,signalGroup);

const hemi=new THREE.HemisphereLight(0x9fcdf2,0x06101b,1.8);scene.add(hemi);const key=new THREE.DirectionalLight(0xd5efff,4.2);key.position.set(15,38,25);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-28;key.shadow.camera.right=28;key.shadow.camera.top=35;key.shadow.camera.bottom=-18;scene.add(key);const rim=new THREE.SpotLight(0x38d9f5,900,75,.55,.8);rim.position.set(-22,14,-18);rim.target.position.set(0,12,0);scene.add(rim,rim.target);const warm=new THREE.PointLight(0xffa857,130,40,2);warm.position.set(0,12,4);scene.add(warm);

const states={exterior:{cam:[33,23,39],target:[3,11,0],title:'พร้อมทำงาน<br>เป็นระบบเดียว',kicker:'ภาพรวมอาคาร · Building overview',desc:'อาคาร 8 ชั้นเชื่อมพลังงาน สภาพแวดล้อม ความปลอดภัย และห้องเครื่องเข้าด้วยกัน'},cutaway:{cam:[31,16,27],target:[3,10,0],title:'ทุกชั้น<br>มองเห็นได้',kicker:'พื้นที่ทำงาน · Occupancy & comfort',desc:'เปิดผิวอาคารเพื่อเห็นพื้นที่ คน และระบบอากาศที่ตอบสนองต่อการใช้งานจริง'},plant:{cam:[21,-1,17],target:[4,-4,0],title:'พบความผิดปกติ<br>ก่อนหยุดทำงาน',kicker:'ห้องเครื่อง B2 · Plant room',desc:'Chiller-03 มีอุณหภูมิสูงกว่าค่าปกติ ระบบเชื่อมผลกระทบและขั้นตอนตรวจสอบไว้ในเหตุการณ์เดียว'}};
let current='exterior',transition=1,startCam=new THREE.Vector3(),startTarget=new THREE.Vector3(),goalCam=new THREE.Vector3(),goalTarget=new THREE.Vector3();
function setView(name){current=name;transition=0;controls.enabled=false;startCam.copy(camera.position);startTarget.copy(controls.target);goalCam.fromArray(states[name].cam);goalTarget.fromArray(states[name].target);document.querySelectorAll('.view').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelector('#systemTitle').innerHTML=states[name].title;document.querySelector('#systemKicker').textContent=states[name].kicker;document.querySelector('#systemDescription').textContent=states[name].desc;document.querySelector('#systemState').textContent=name==='plant'?'ตรวจพบ 1 เหตุการณ์':'ทุกระบบทำงานปกติ';alert.visible=name==='plant';floors.forEach(f=>{const glass=f.children.find(c=>c.name==='glass-shell');if(glass)glass.visible=name!=='cutaway'});signalGroup.visible=name!=='plant'}
document.querySelectorAll('.view').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelector('#autoRotate').addEventListener('click',e=>{controls.autoRotate=!controls.autoRotate;e.currentTarget.setAttribute('aria-pressed',String(controls.autoRotate))});
const clock=new THREE.Clock();function frame(){requestAnimationFrame(frame);const dt=Math.min(clock.getDelta(),.04);if(transition<1){transition=Math.min(1,transition+dt*.85);const t=1-Math.pow(1-transition,3);camera.position.lerpVectors(startCam,goalCam,t);controls.target.lerpVectors(startTarget,goalTarget,t);camera.lookAt(controls.target);if(transition===1){const d=camera.position.clone().sub(controls.target);controls.radius=d.length();controls.phi=Math.acos(d.y/controls.radius);controls.theta=Math.atan2(d.x,d.z);controls.enabled=true}}signalGroup.children.forEach((s,i)=>{if(s.isMesh&&s.geometry.type==='SphereGeometry')s.scale.setScalar(.75+.25*Math.sin(clock.elapsedTime*2+i))});controls.update();renderer.render(scene,camera)}frame();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.7))});
